// src/templates/angular/components/app.component.ts
import { Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';
import { CounterComponent } from './counter.component';

@Component({
	selector: 'app-root',
	standalone: true,
	imports: [CommonModule, CounterComponent],
	templateUrl: './app.component.html',
	styleUrls: ['./app.component.css']
})
export class AppComponent {
	@Input() initialCount: number = 0;
}


<main>
	<nav>
		<a href="https://absolutejs.com" target="_blank">
			<img
				class="logo"
				src="/assets/png/absolutejs-temp.png"
				alt="AbsoluteJS Logo"
			/>
		</a>
		<a href="https://angular.dev/">
			<img
				class="logo angular"
				src="/assets/svg/angular.svg"
				alt="Angular Logo"
			/>
		</a>
	</nav>
	<h1>AbsoluteJS + Angular</h1>
	<app-counter [initialCount]="initialCount"></app-counter>
	<p>
		Edit <code>example/angular/pages/AngularExample.ts</code> then save
		and refresh to update the page.
	</p>
	<p style="color: #777;">
		( Hot Module Reloading is coming soon )
	</p>
	<p style="margin-top: 2rem;">
		Explore the other pages to see how AbsoluteJS seamlessly unifies
		multiple frameworks on a single server.
	</p>
	<p style="color: #777; font-size: 1rem; margin-top: 2rem;">
		Click on the AbsoluteJS and Angular logos to learn more.
	</p>
</main>

// src/templates/react/components/App.tsx
import { useState } from 'react';

type AppProps = { initialCount: number };

export const App = ({ initialCount }: AppProps) => {
	const [count, setCount] = useState(initialCount);

	return (
		<main>
			<nav>
				<a href="https://absolutejs.com" target="_blank">
					<img
						alt="AbsoluteJS Logo"
						className="logo"
						src="/assets/png/absolutejs-temp.png"
					/>
				</a>
				<a href="https://react.dev/">
					<img
						alt="React Logo"
						className="logo react"
						src="/assets/svg/react.svg"
					/>
				</a>
			</nav>
			<h1>AbsoluteJS + React</h1>
			<button onClick={() => setCount(count + 1)}>
				count is {count}
			</button>
			<p>
				Edit <code>example/react/pages/ReactExample.tsx</code> and save
				to test HMR.
			</p>
			<p style={{ marginTop: '2rem' }}>
				Explore the other pages to see multiple frameworks running
				together.
			</p>
			<p
				style={{
					color: '#777',
					fontSize: '1rem',
					marginTop: '2rem'
				}}
			>
				Click on the AbsoluteJS and React logos to learn more.
			</p>
		</main>
	);
};
