// src/templates/angular/components/head.component.ts
import { Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
	selector: 'app-head',
	standalone: true,
	imports: [CommonModule],
	template: `
		<head>
			<meta charset="UTF-8" />
			<link rel="icon" type="image/x-icon" href="/assets/ico/favicon.ico" />
			<meta name="viewport" content="width=device-width, initial-scale=1.0" />
			<title>AbsoluteJS</title>
			<link rel="stylesheet" [href]="cssPath" />
		</head>
	`
})
export class HeadComponent {
	@Input() cssPath: string = '';
}

// src/templates/react/components/utils/Head.tsx
import { styleReset } from '../../styles/default/styleReset';

type HeadProps = {
	title?: string;
	icon?: string;
	font?: string;
};

export const Head = ({
	title = 'AbsoluteJS',
	icon = '/assets/ico/favicon.ico',
	font = 'Poppins'
}: HeadProps) => (
	<head>
		<meta charSet="utf-8" />
		<title>{title}</title>
		<meta name="description" content="Bun, Elysia & React" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<link rel="icon" href={icon} />
		<link rel="preconnect" href="https://fonts.googleapis.com" />
		<link
			rel="preconnect"
			href="https://fonts.gstatic.com"
			crossOrigin="anonymous"
		/>
		<link
			href={`https://fonts.googleapis.com/css2?family=${font}:wght@100..900&display=swap`}
			rel="stylesheet"
		/>
		<style>{styleReset}</style>
	</head>
);
